<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protofile.proto

namespace GPBMetadata;

class Protofile
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aee010a0f70726f746f66696c652e70726f746f120970726f746f66696c" .
            "65221c0a0c48656c6c6f52657175657374120c0a046e616d651801200128" .
            "09221d0a0a48656c6c6f5265706c79120f0a076d65737361676518012001" .
            "2809328a010a0747726565746572123c0a0853617948656c6c6f12172e70" .
            "726f746f66696c652e48656c6c6f526571756573741a152e70726f746f66" .
            "696c652e48656c6c6f5265706c79220012410a0d53617948656c6c6f4167" .
            "61696e12172e70726f746f66696c652e48656c6c6f526571756573741a15" .
            "2e70726f746f66696c652e48656c6c6f5265706c792200620670726f746f" .
            "33"
        ), true);

        static::$is_initialized = true;
    }
}

